### PR TITLE
社区和survey的一些更新

### PR DESCRIPTION
**Pull request by brucx**

### CODE REVIEW

**Comment by sunyuan3** [comment]
Hi @brucx , I need to rebase this repo.

**Comment by sunyuan3** [comment]
Hi @brucx , could you please rebase it? If you need my help, please tell me.

**Comment by brucx** [comment]
@sunyuan3 You can check it and merge now

**Comment by sunyuan3** [comment]
@brucx , there are 4 commits in this pull request. Please use one commit in this pull request.
BTW, you can use the following command to force to refresh your pku-osa:master branch with one commit.
git push -f origin ${local_branch_name}:${remote_branch_name}

**Comment by brucx** [comment]
I don't know it well, why don't you _squash and merge_?

**Comment by sunyuan3** [comment]
Ok. It has been merged.

**Pull request merged**
